[phases.setup]
nixPkgs = ["python39", "postgresql", "gcc"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput", "python manage.py migrate"]

[start]
cmd = "gunicorn medical_law_project.wsgi:application --bind 0.0.0.0:$PORT" 