# Generated by Django 4.2 on 2025-07-01 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('job_request_submitted', '채용 요청 제출'), ('job_request_accepted', '채용 요청 접수'), ('candidate_recommended', '후보자 추천'), ('document_review_completed', '서류 검토 완료'), ('interview_scheduled', '면접 일정 확정'), ('interview_completed', '면접 완료'), ('final_decision_made', '최종 결정'), ('workflow_step_completed', '워크플로우 단계 완료'), ('system_notification', '시스템 알림'), ('reminder', '리마인더')], max_length=30, verbose_name='알림 유형')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('message', models.TextField(verbose_name='메시지')),
                ('priority', models.CharField(choices=[('low', '낮음'), ('normal', '보통'), ('high', '높음'), ('urgent', '긴급')], default='normal', max_length=10, verbose_name='우선순위')),
                ('action_required', models.BooleanField(default=False, verbose_name='액션 필요')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='액션 URL')),
                ('action_text', models.CharField(blank=True, max_length=100, verbose_name='액션 텍스트')),
                ('related_object_type', models.CharField(blank=True, max_length=50, verbose_name='관련 객체 타입')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='관련 객체 ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음 여부')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='읽은 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='예약 발송 시간')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='발송 시간')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.organization', verbose_name='소속 기관')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='수신자')),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='템플릿명')),
                ('notification_type', models.CharField(choices=[('job_request_submitted', '채용 요청 제출'), ('job_request_accepted', '채용 요청 접수'), ('candidate_recommended', '후보자 추천'), ('document_review_completed', '서류 검토 완료'), ('interview_scheduled', '면접 일정 확정'), ('interview_completed', '면접 완료'), ('final_decision_made', '최종 결정'), ('workflow_step_completed', '워크플로우 단계 완료'), ('system_notification', '시스템 알림'), ('reminder', '리마인더')], max_length=30, verbose_name='알림 유형')),
                ('title_template', models.CharField(max_length=200, verbose_name='제목 템플릿')),
                ('message_template', models.TextField(verbose_name='메시지 템플릿')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('variables_description', models.TextField(blank=True, verbose_name='변수 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '알림 템플릿',
                'verbose_name_plural': '알림 템플릿들',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='이메일 알림')),
                ('web_notifications', models.BooleanField(default=True, verbose_name='웹 알림')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='SMS 알림')),
                ('job_request_notifications', models.BooleanField(default=True, verbose_name='채용 요청 알림')),
                ('candidate_notifications', models.BooleanField(default=True, verbose_name='후보자 관련 알림')),
                ('interview_notifications', models.BooleanField(default=True, verbose_name='면접 관련 알림')),
                ('workflow_notifications', models.BooleanField(default=True, verbose_name='워크플로우 알림')),
                ('system_notifications', models.BooleanField(default=True, verbose_name='시스템 알림')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='방해 금지 시작 시간')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='방해 금지 종료 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '알림 설정',
                'verbose_name_plural': '알림 설정들',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.CharField(choices=[('email', '이메일'), ('web', '웹'), ('sms', 'SMS'), ('websocket', 'WebSocket')], max_length=20, verbose_name='발송 방법')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('sent', '발송됨'), ('failed', '실패'), ('delivered', '전달됨'), ('read', '읽음')], default='pending', max_length=20, verbose_name='상태')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='발송 시간')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='전달 시간')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='notifications.notification', verbose_name='알림')),
            ],
            options={
                'verbose_name': '알림 발송 로그',
                'verbose_name_plural': '알림 발송 로그들',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization', 'created_at'], name='notificatio_organiz_b709e0_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'created_at'], name='notificatio_notific_f2e0f7_idx'),
        ),
    ]
