# Generated by Django 4.2.7 on 2025-07-07 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_useractivity_related_object_name_and_more'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='채팅방명')),
                ('room_type', models.CharField(choices=[('workflow', '워크플로우'), ('candidate', '후보자'), ('interview', '면접'), ('general', '일반'), ('support', '지원')], max_length=20, verbose_name='채팅방 유형')),
                ('related_object_type', models.CharField(blank=True, max_length=50, verbose_name='관련 객체 타입')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='관련 객체 ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('is_private', models.BooleanField(default=False, verbose_name='비공개')),
                ('max_participants', models.PositiveIntegerField(default=50, verbose_name='최대 참여자 수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_chat_rooms', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '채팅방',
                'verbose_name_plural': '채팅방들',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='그룹명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('auto_add_new_users', models.BooleanField(default=False, verbose_name='신규 사용자 자동 추가')),
                ('notification_types', models.JSONField(default=list, verbose_name='알림 유형')),
                ('priority_filter', models.CharField(choices=[('low', '낮음'), ('normal', '보통'), ('high', '높음'), ('urgent', '긴급')], default='normal', max_length=10, verbose_name='우선순위 필터')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('members', models.ManyToManyField(related_name='notification_groups', to=settings.AUTH_USER_MODEL, verbose_name='멤버')),
            ],
            options={
                'verbose_name': '알림 그룹',
                'verbose_name_plural': '알림 그룹들',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoomParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', '관리자'), ('moderator', '운영자'), ('member', '일반 멤버'), ('guest', '게스트')], default='member', max_length=20, verbose_name='역할')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='참여일')),
                ('last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 읽은 시간')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 참여자')),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_relations', to='notifications.chatroom', verbose_name='채팅방')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room_relations', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '채팅방 참여자',
                'verbose_name_plural': '채팅방 참여자들',
                'unique_together': {('chat_room', 'user')},
            },
        ),
        migrations.AddField(
            model_name='chatroom',
            name='participants',
            field=models.ManyToManyField(related_name='chat_rooms', through='notifications.ChatRoomParticipant', to=settings.AUTH_USER_MODEL, verbose_name='참여자'),
        ),
        migrations.CreateModel(
            name='NotificationAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('total_notifications', models.PositiveIntegerField(default=0, verbose_name='총 알림 수')),
                ('read_notifications', models.PositiveIntegerField(default=0, verbose_name='읽은 알림 수')),
                ('unread_notifications', models.PositiveIntegerField(default=0, verbose_name='읽지 않은 알림 수')),
                ('notification_type_counts', models.JSONField(default=dict, verbose_name='알림 유형별 개수')),
                ('priority_counts', models.JSONField(default=dict, verbose_name='우선순위별 개수')),
                ('delivery_method_counts', models.JSONField(default=dict, verbose_name='전송 방법별 개수')),
                ('avg_response_time_minutes', models.FloatField(default=0, verbose_name='평균 응답 시간(분)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_analytics', to='accounts.organization', verbose_name='소속 기관')),
            ],
            options={
                'verbose_name': '알림 분석',
                'verbose_name_plural': '알림 분석들',
                'ordering': ['-date'],
                'unique_together': {('date', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', '텍스트'), ('file', '파일'), ('image', '이미지'), ('system', '시스템 메시지'), ('notification', '알림')], default='text', max_length=20, verbose_name='메시지 유형')),
                ('content', models.TextField(verbose_name='내용')),
                ('file_url', models.CharField(blank=True, max_length=500, verbose_name='파일 URL')),
                ('file_name', models.CharField(blank=True, max_length=200, verbose_name='파일명')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='파일 크기')),
                ('is_edited', models.BooleanField(default=False, verbose_name='수정됨')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제됨')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='수정일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='notifications.chatroom', verbose_name='채팅방')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='발신자')),
            ],
            options={
                'verbose_name': '채팅 메시지',
                'verbose_name_plural': '채팅 메시지들',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['chat_room', 'created_at'], name='notificatio_chat_ro_bda868_idx'), models.Index(fields=['sender', 'created_at'], name='notificatio_sender__f76ea5_idx')],
            },
        ),
    ]
