# Generated by Django 4.2 on 2025-07-01 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='성명')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='이메일')),
                ('phone', models.CharField(max_length=20, verbose_name='연락처')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('address', models.TextField(blank=True, verbose_name='주소')),
                ('gender', models.CharField(blank=True, choices=[('male', '남성'), ('female', '여성')], max_length=10, verbose_name='성별')),
                ('education_level', models.CharField(choices=[('high_school', '고등학교'), ('college', '전문대학'), ('university', '대학교'), ('graduate', '대학원'), ('phd', '박사')], max_length=30, verbose_name='최종학력')),
                ('major', models.CharField(blank=True, max_length=50, verbose_name='전공')),
                ('university', models.CharField(blank=True, max_length=100, verbose_name='졸업학교')),
                ('graduation_year', models.IntegerField(blank=True, null=True, verbose_name='졸업년도')),
                ('total_experience_years', models.IntegerField(default=0, help_text='관련 분야 총 경력', verbose_name='총 경력(년)')),
                ('relevant_experience', models.TextField(verbose_name='관련 경력')),
                ('current_company', models.CharField(blank=True, max_length=100, verbose_name='현재 회사')),
                ('current_position', models.CharField(blank=True, max_length=50, verbose_name='현재 직책')),
                ('licenses', models.TextField(blank=True, verbose_name='보유 자격증')),
                ('skills', models.TextField(blank=True, verbose_name='보유 스킬')),
                ('languages', models.TextField(blank=True, verbose_name='언어 능력')),
                ('resume_file', models.FileField(upload_to='resumes/', verbose_name='이력서 파일')),
                ('portfolio_file', models.FileField(blank=True, upload_to='portfolios/', verbose_name='포트폴리오 파일')),
                ('cover_letter', models.FileField(blank=True, upload_to='cover_letters/', verbose_name='자기소개서')),
                ('recommendation_reason', models.TextField(verbose_name='추천 사유')),
                ('expected_salary', models.IntegerField(blank=True, help_text='연봉 기준 (만원)', null=True, verbose_name='희망 급여')),
                ('available_start_date', models.DateField(blank=True, null=True, verbose_name='입사 가능일')),
                ('status', models.CharField(choices=[('recommended', '추천완료'), ('document_review', '서류검토중'), ('document_passed', '서류합격'), ('document_failed', '서류불합격'), ('interview_scheduled', '면접예정'), ('interviewed', '면접완료'), ('final_passed', '최종합격'), ('final_failed', '최종불합격'), ('hired', '입사확정'), ('withdrawn', '지원철회')], default='recommended', max_length=20, verbose_name='진행 상태')),
                ('internal_notes', models.TextField(blank=True, verbose_name='내부 메모')),
                ('candidate_notes', models.TextField(blank=True, verbose_name='후보자 메모')),
                ('recommended_at', models.DateTimeField(auto_now_add=True, verbose_name='추천일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('job_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='workflow.jobrequest', verbose_name='채용 요청')),
                ('recommended_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_candidates', to=settings.AUTH_USER_MODEL, verbose_name='추천자')),
            ],
            options={
                'verbose_name': '후보자',
                'verbose_name_plural': '후보자들',
                'ordering': ['-recommended_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('internal', '내부 메모'), ('candidate', '후보자 메모'), ('evaluation', '평가 메모'), ('interview', '면접 메모'), ('general', '일반 메모')], max_length=20, verbose_name='메모 유형')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('is_private', models.BooleanField(default=False, verbose_name='비공개')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='candidates.candidate', verbose_name='후보자')),
            ],
            options={
                'verbose_name': '후보자 메모',
                'verbose_name_plural': '후보자 메모들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('status_change', '상태 변경'), ('note_added', '메모 추가'), ('file_uploaded', '파일 업로드'), ('interview_scheduled', '면접 일정'), ('evaluation_added', '평가 추가'), ('decision_made', '결정 사항')], max_length=20, verbose_name='액션')),
                ('old_value', models.CharField(blank=True, max_length=100, verbose_name='이전 값')),
                ('new_value', models.CharField(blank=True, max_length=100, verbose_name='새 값')),
                ('description', models.TextField(verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='실행자')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='candidates.candidate', verbose_name='후보자')),
            ],
            options={
                'verbose_name': '후보자 이력',
                'verbose_name_plural': '후보자 이력들',
                'ordering': ['-created_at'],
            },
        ),
    ]
