# Generated by Django 4.2.7 on 2025-07-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='branch',
            field=models.CharField(choices=[('hongdae', '홍대점'), ('gangnam', '강남점'), ('bundang', '분당점'), ('other', '기타')], default='hongdae', max_length=20, verbose_name='지점'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.CharField(choices=[('total_manager', '총괄실장'), ('counseling_manager', '상담실장'), ('skin_manager', '피부매니저'), ('skin_staff', '피부팀원'), ('nurse_manager', '간호팀장'), ('nurse_staff', '간호조무사'), ('coordinator', '코디네이터')], default='skin_staff', max_length=30, verbose_name='지원 직무'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('waiting', '대기'), ('approved', '승인됨'), ('rejected', '거절됨'), ('evaluating', '평가 중'), ('interview_scheduled', '면접 예정'), ('interviewed', '면접 완료'), ('final_approved', '최종 승인'), ('final_rejected', '최종 거절'), ('hired', '채용됨'), ('withdrawn', '지원 철회')], default='waiting', max_length=20, verbose_name='진행 상태'),
        ),
    ]
