# Generated by Django 4.2.7 on 2025-07-07 16:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidates', '0002_candidate_branch_candidate_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='interview_comments',
            field=models.TextField(blank=True, verbose_name='면접 의견'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='interview_decision',
            field=models.CharField(choices=[('pending', '대기'), ('pass', '합격'), ('fail', '불합격'), ('hold', '보류')], default='pending', max_length=20, verbose_name='면접 결정'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='interview_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='면접 점수'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='review_comments',
            field=models.TextField(blank=True, verbose_name='검토 의견'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='review_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='검토일'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='review_score',
            field=models.IntegerField(blank=True, help_text='100점 만점', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='검토 점수'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='review_status',
            field=models.CharField(choices=[('pending', '검토 대기'), ('in_progress', '검토중'), ('passed', '검토 통과'), ('failed', '검토 실패'), ('needs_more_info', '추가정보 필요')], default='pending', max_length=20, verbose_name='검토 상태'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_candidates', to=settings.AUTH_USER_MODEL, verbose_name='검토자'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('waiting', '대기'), ('under_review', '검토중'), ('approved', '승인됨'), ('rejected', '거절됨'), ('evaluating', '평가 중'), ('interview_scheduled', '면접 예정'), ('interviewed', '면접 완료'), ('final_approved', '최종 승인'), ('final_rejected', '최종 거절'), ('hired', '채용됨'), ('withdrawn', '지원 철회')], default='waiting', max_length=20, verbose_name='진행 상태'),
        ),
        migrations.CreateModel(
            name='CandidateReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('initial', '초기 검토'), ('document', '서류 검토'), ('technical', '기술 검토'), ('final', '최종 검토')], max_length=20, verbose_name='검토 유형')),
                ('experience_score', models.IntegerField(default=0, help_text='25점 만점', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)], verbose_name='경력 점수')),
                ('education_score', models.IntegerField(default=0, help_text='20점 만점', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='학력 점수')),
                ('skill_score', models.IntegerField(default=0, help_text='25점 만점', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)], verbose_name='스킬 점수')),
                ('personality_score', models.IntegerField(default=0, help_text='15점 만점', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='인성 점수')),
                ('motivation_score', models.IntegerField(default=0, help_text='15점 만점', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='동기 점수')),
                ('total_score', models.IntegerField(default=0, verbose_name='총점')),
                ('passed', models.BooleanField(default=False, verbose_name='합격 여부')),
                ('strengths', models.TextField(blank=True, verbose_name='강점')),
                ('weaknesses', models.TextField(blank=True, verbose_name='약점')),
                ('improvement_areas', models.TextField(blank=True, verbose_name='개선 영역')),
                ('overall_comments', models.TextField(blank=True, verbose_name='종합 의견')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='검토일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='candidates.candidate', verbose_name='후보자')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='검토자')),
            ],
            options={
                'verbose_name': '후보자 검토',
                'verbose_name_plural': '후보자 검토들',
                'ordering': ['-reviewed_at'],
            },
        ),
    ]
