# Generated by Django 4.2.23 on 2025-07-10 01:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField(verbose_name='입력 텍스트')),
                ('input_type', models.CharField(choices=[('text', '텍스트'), ('file', '파일'), ('url', 'URL')], max_length=20, verbose_name='입력 타입')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='파일명')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('overall_score', models.IntegerField(verbose_name='전체 점수')),
                ('compliance_status', models.CharField(choices=[('적합', '적합'), ('부분적합', '부분적합'), ('부적합', '부적합')], max_length=20, verbose_name='준수 상태')),
                ('risk_level', models.CharField(choices=[('low', '낮음'), ('medium', '보통'), ('high', '높음')], max_length=20, verbose_name='위험도')),
                ('violations', models.JSONField(default=list, verbose_name='위반 항목')),
                ('recommendations', models.JSONField(default=list, verbose_name='개선 권장사항')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일시')),
                ('analysis_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='분석일시')),
            ],
            options={
                'verbose_name': '준수 분석 결과',
                'verbose_name_plural': '준수 분석 결과들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('document_type', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Word'), ('txt', '텍스트'), ('hwp', '한글')], max_length=20, verbose_name='문서 타입')),
                ('file', models.FileField(upload_to='guidelines/', verbose_name='파일')),
                ('extracted_text', models.TextField(blank=True, verbose_name='추출된 텍스트')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='업로드일시')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
            ],
            options={
                'verbose_name': '의료 가이드라인',
                'verbose_name_plural': '의료 가이드라인들',
                'ordering': ['-upload_date'],
            },
        ),
    ]
