# Generated by Django 4.2.23 on 2025-07-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_checker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalguideline',
            options={'ordering': ['-uploaded_at'], 'verbose_name': '의료 가이드라인', 'verbose_name_plural': '의료 가이드라인들'},
        ),
        migrations.RenameField(
            model_name='medicalguideline',
            old_name='upload_date',
            new_name='uploaded_at',
        ),
        migrations.AddField(
            model_name='medicalguideline',
            name='category',
            field=models.CharField(choices=[('medical_law', '의료법'), ('advertising_law', '의료광고법'), ('guidelines', '가이드라인'), ('notices', '공지사항'), ('cases', '판례')], default='guidelines', max_length=50, verbose_name='카테고리'),
        ),
        migrations.AddField(
            model_name='medicalguideline',
            name='description',
            field=models.TextField(blank=True, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='medicalguideline',
            name='document_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Word'), ('txt', '텍스트')], max_length=20, verbose_name='문서 타입'),
        ),
    ]
