# Generated by Django 4.2.23 on 2025-07-10 02:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_checker', '0002_alter_medicalguideline_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='위반 카테고리')),
                ('title', models.CharField(max_length=200, verbose_name='규칙 제목')),
                ('description', models.TextField(verbose_name='규칙 설명')),
                ('severity', models.CharField(choices=[('high', '고위험'), ('medium', '중위험'), ('low', '저위험')], max_length=20, verbose_name='심각도')),
                ('penalty', models.TextField(verbose_name='처벌 내용')),
                ('legal_basis', models.TextField(verbose_name='법적 근거')),
                ('improvement_guide', models.TextField(verbose_name='개선 가이드')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '준수 규칙',
                'verbose_name_plural': '준수 규칙들',
                'ordering': ['category', 'severity', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MedicalLawInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('category', models.CharField(choices=[('medical_law', '의료법'), ('advertising_law', '의료광고법'), ('guidelines', '가이드라인'), ('notices', '공지사항'), ('penalties', '처벌 기준'), ('review_process', '심의 절차')], max_length=50, verbose_name='카테고리')),
                ('content', models.TextField(verbose_name='내용')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='출처')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='시행일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '의료법 정보',
                'verbose_name_plural': '의료법 정보들',
                'ordering': ['category', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RecommendedExpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='카테고리')),
                ('original_text', models.CharField(max_length=200, verbose_name='원문 표현')),
                ('improved_text', models.CharField(max_length=200, verbose_name='개선 표현')),
                ('reason', models.TextField(verbose_name='개선 이유')),
                ('importance', models.CharField(choices=[('high', '높음'), ('medium', '보통'), ('low', '낮음')], default='medium', max_length=20, verbose_name='중요도')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '권장 표현',
                'verbose_name_plural': '권장 표현들',
                'ordering': ['category', 'importance', 'original_text'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, verbose_name='키워드')),
                ('description', models.TextField(blank=True, verbose_name='키워드 설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일시')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='compliance_checker.compliancerule', verbose_name='관련 규칙')),
            ],
            options={
                'verbose_name': '위반 키워드',
                'verbose_name_plural': '위반 키워드들',
                'ordering': ['rule', 'keyword'],
            },
        ),
    ]
