# Generated by Django 4.2.23 on 2025-07-10 03:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_checker', '0003_compliancerule_medicallawinfo_recommendedexpression_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidelineDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('category', models.CharField(choices=[('guidelines', '가이드라인'), ('laws', '법령'), ('precedents', '판례'), ('penalties', '처벌사례'), ('notices', '공지사항'), ('reviews', '심의안내')], max_length=50, verbose_name='카테고리')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('content', models.TextField(verbose_name='내용')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='출처')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='시행일')),
                ('file', models.FileField(blank=True, null=True, upload_to='guidelines/', verbose_name='첨부파일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '가이드라인 문서',
                'verbose_name_plural': '가이드라인 문서들',
                'ordering': ['category', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuidelineUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('content_update', '내용 업데이트'), ('new_document', '새 문서 추가'), ('category_change', '카테고리 변경'), ('status_change', '상태 변경')], max_length=50, verbose_name='업데이트 유형')),
                ('previous_content', models.TextField(blank=True, verbose_name='이전 내용')),
                ('new_content', models.TextField(blank=True, verbose_name='새 내용')),
                ('update_reason', models.TextField(blank=True, verbose_name='업데이트 사유')),
                ('updated_by', models.CharField(blank=True, max_length=100, verbose_name='업데이트자')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='업데이트일시')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='compliance_checker.guidelinedocument', verbose_name='문서')),
            ],
            options={
                'verbose_name': '가이드라인 업데이트',
                'verbose_name_plural': '가이드라인 업데이트들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='카테고리명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일시')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='compliance_checker.compliancecategory', verbose_name='상위 카테고리')),
            ],
            options={
                'verbose_name': '준수 카테고리',
                'verbose_name_plural': '준수 카테고리들',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('content_analysis', '내용 분석'), ('compliance_check', '준수성 검토'), ('risk_assessment', '위험도 평가'), ('improvement_suggestions', '개선 제안')], max_length=50, verbose_name='분석 유형')),
                ('analysis_result', models.JSONField(verbose_name='분석 결과')),
                ('ai_model_used', models.CharField(max_length=100, verbose_name='사용된 AI 모델')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='처리 시간(초)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='분석일시')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='compliance_checker.guidelinedocument', verbose_name='문서')),
            ],
            options={
                'verbose_name': 'AI 분석 결과',
                'verbose_name_plural': 'AI 분석 결과들',
                'ordering': ['-created_at'],
            },
        ),
    ]
