# Generated by Django 4.2 on 2025-07-01 09:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0001_initial'),
        ('candidates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='템플릿명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_default', models.BooleanField(default=False, verbose_name='기본 템플릿')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('criteria_config', models.JSONField(default=dict, verbose_name='평가 기준 설정')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '평가 템플릿',
                'verbose_name_plural': '평가 템플릿들',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField(verbose_name='면접 일시')),
                ('duration_minutes', models.IntegerField(default=30, help_text='분 단위', verbose_name='면접 시간')),
                ('interview_type', models.CharField(choices=[('in_person', '대면'), ('video', '화상'), ('phone', '전화'), ('hybrid', '혼합')], max_length=20, verbose_name='면접 유형')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='면접 장소')),
                ('status', models.CharField(choices=[('scheduled', '예정'), ('in_progress', '진행중'), ('completed', '완료'), ('cancelled', '취소'), ('no_show', '미참석'), ('rescheduled', '재일정')], default='scheduled', max_length=20, verbose_name='상태')),
                ('actual_start_time', models.DateTimeField(blank=True, null=True, verbose_name='실제 시작 시간')),
                ('actual_end_time', models.DateTimeField(blank=True, null=True, verbose_name='실제 종료 시간')),
                ('pre_interview_notes', models.TextField(blank=True, verbose_name='면접 전 메모')),
                ('post_interview_notes', models.TextField(blank=True, verbose_name='면접 후 메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='candidates.candidate', verbose_name='후보자')),
                ('job_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='workflow.jobrequest', verbose_name='채용 요청')),
                ('primary_interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_interviews', to=settings.AUTH_USER_MODEL, verbose_name='주 면접관')),
                ('secondary_interviewers', models.ManyToManyField(blank=True, related_name='secondary_interviews', to=settings.AUTH_USER_MODEL, verbose_name='부 면접관')),
            ],
            options={
                'verbose_name': '면접',
                'verbose_name_plural': '면접들',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='InterviewEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_experience_score', models.IntegerField(default=0, help_text='치원부야 (경력) - 20점 만점', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='경력 점수')),
                ('intellectual_ability_score', models.IntegerField(default=0, help_text='지적증 여부 (지적 능력) - 20점 만점', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='지적 능력 점수')),
                ('transportation_score', models.IntegerField(default=0, help_text='자동차 여부 (교통수단) - 15점 만점', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='교통수단 점수')),
                ('communication_score', models.IntegerField(default=0, help_text='의사소통 능력 - 10점 만점', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='의사소통 점수')),
                ('personality_score', models.IntegerField(default=0, help_text='인성 평가 - 10점 만점', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='인성 점수')),
                ('overall_impression_score', models.IntegerField(default=0, help_text='종합 인상 - 10점 만점', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='종합 인상 점수')),
                ('total_score', models.IntegerField(default=0, verbose_name='총점')),
                ('overall_rating', models.CharField(choices=[('excellent', '매우 양호'), ('good', '양호'), ('average', '보통'), ('poor', '불량'), ('very_poor', '매우 불량')], max_length=20, verbose_name='종합 평가')),
                ('strengths', models.TextField(blank=True, verbose_name='장점')),
                ('weaknesses', models.TextField(blank=True, verbose_name='단점')),
                ('recommendations', models.TextField(blank=True, verbose_name='종합 의견')),
                ('hire_recommendation', models.BooleanField(default=False, verbose_name='채용 추천')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True, verbose_name='평가일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='평가자')),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='evaluations.interview', verbose_name='면접')),
            ],
            options={
                'verbose_name': '면접 평가',
                'verbose_name_plural': '면접 평가들',
                'ordering': ['-evaluated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_experience_score', models.IntegerField(default=0, help_text='치원부야 (경력) - 20점 만점', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='경력 점수')),
                ('education_score', models.IntegerField(default=0, help_text='학력 - 15점 만점', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='학력 점수')),
                ('skill_score', models.IntegerField(default=0, help_text='스킬 - 10점 만점', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='스킬 점수')),
                ('total_score', models.IntegerField(default=0, verbose_name='총점')),
                ('passed', models.BooleanField(default=False, verbose_name='합격 여부')),
                ('review_comments', models.TextField(blank=True, verbose_name='검토 의견')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='검토일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_review', to='candidates.candidate', verbose_name='후보자')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='검토자')),
            ],
            options={
                'verbose_name': '서류 검토',
                'verbose_name_plural': '서류 검토들',
                'ordering': ['-reviewed_at'],
            },
        ),
    ]
