# Generated by Django 4.2.7 on 2025-07-07 02:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidates', '0002_candidate_branch_candidate_position_and_more'),
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewScheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_dates', models.JSONField(default=list, help_text='후보자가 선호하는 면접 일정 목록', verbose_name='선호 일정')),
                ('interviewer_availability', models.JSONField(default=list, help_text='면접관들의 가능한 일정 목록', verbose_name='면접관 가능 일정')),
                ('proposed_date', models.DateTimeField(blank=True, null=True, verbose_name='제안된 일정')),
                ('confirmed_date', models.DateTimeField(blank=True, null=True, verbose_name='확정된 일정')),
                ('scheduling_status', models.CharField(choices=[('pending', '대기중'), ('candidate_contacted', '후보자 연락완료'), ('date_proposed', '일정 제안됨'), ('date_confirmed', '일정 확정됨'), ('date_rejected', '일정 거절됨'), ('rescheduled', '재일정'), ('cancelled', '취소됨')], default='pending', max_length=20, verbose_name='조율 상태')),
                ('contact_method', models.CharField(choices=[('phone', '전화'), ('email', '이메일'), ('sms', '문자'), ('kakao', '카카오톡')], max_length=20, verbose_name='연락 방법')),
                ('contact_attempts', models.IntegerField(default=0, verbose_name='연락 시도 횟수')),
                ('last_contact_date', models.DateTimeField(blank=True, null=True, verbose_name='마지막 연락일')),
                ('candidate_response', models.TextField(blank=True, verbose_name='후보자 응답')),
                ('scheduling_notes', models.TextField(blank=True, verbose_name='일정 조율 메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview_scheduling', to='candidates.candidate', verbose_name='후보자')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='일정 조율자')),
            ],
            options={
                'verbose_name': '면접 일정 조율',
                'verbose_name_plural': '면접 일정 조율들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screening_status', models.CharField(choices=[('pending', '대기중'), ('in_progress', '검토중'), ('passed', '합격'), ('failed', '불합격'), ('needs_more_info', '추가정보 필요')], default='pending', max_length=20, verbose_name='심사 상태')),
                ('resume_quality_score', models.IntegerField(default=0, help_text='이력서 완성도 및 내용 - 20점 만점', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='이력서 품질 점수')),
                ('experience_match_score', models.IntegerField(default=0, help_text='지원 직무와의 경력 일치도 - 25점 만점', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)], verbose_name='경력 적합성 점수')),
                ('education_score', models.IntegerField(default=0, help_text='학력 및 전공 적합성 - 15점 만점', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='학력 점수')),
                ('skill_match_score', models.IntegerField(default=0, help_text='필요 스킬 보유 여부 - 20점 만점', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='스킬 적합성 점수')),
                ('overall_impression_score', models.IntegerField(default=0, help_text='전체적인 인상 및 잠재력 - 20점 만점', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='종합 인상 점수')),
                ('total_score', models.IntegerField(default=0, verbose_name='총점')),
                ('passing_score', models.IntegerField(default=70, verbose_name='합격 점수')),
                ('passed', models.BooleanField(default=False, verbose_name='합격 여부')),
                ('strengths', models.TextField(blank=True, verbose_name='장점')),
                ('weaknesses', models.TextField(blank=True, verbose_name='단점')),
                ('improvement_suggestions', models.TextField(blank=True, verbose_name='개선 제안')),
                ('screening_notes', models.TextField(blank=True, verbose_name='심사 메모')),
                ('additional_info_requested', models.TextField(blank=True, verbose_name='추가 정보 요청사항')),
                ('info_deadline', models.DateField(blank=True, null=True, verbose_name='정보 제출 마감일')),
                ('screening_started_at', models.DateTimeField(blank=True, null=True, verbose_name='심사 시작일')),
                ('screening_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='심사 완료일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_screening', to='candidates.candidate', verbose_name='후보자')),
                ('screener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='심사자')),
            ],
            options={
                'verbose_name': '서류 심사',
                'verbose_name_plural': '서류 심사들',
                'ordering': ['-created_at'],
            },
        ),
    ]
