# Generated by Django 4.2.7 on 2025-07-07 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('report_type', models.CharField(choices=[('monthly_performance', '월간 성과 보고서'), ('candidate_analysis', '후보자 분석 보고서'), ('workflow_analysis', '워크플로우 분석'), ('interview_schedule', '면접 일정 보고서'), ('custom', '커스텀 보고서')], max_length=30, verbose_name='보고서 유형')),
                ('status', models.CharField(choices=[('draft', '작성중'), ('generating', '생성중'), ('completed', '완료'), ('failed', '실패')], default='draft', max_length=20, verbose_name='상태')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='파일 경로')),
                ('file_size', models.IntegerField(default=0, verbose_name='파일 크기')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='시작일')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('include_charts', models.BooleanField(default=True, verbose_name='차트 포함')),
                ('include_details', models.BooleanField(default=True, verbose_name='상세 정보 포함')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='생성 완료일')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '보고서',
                'verbose_name_plural': '보고서들',
                'ordering': ['-created_at'],
            },
        ),
    ]
