# Generated by Django 4.2 on 2025-07-01 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('status', models.CharField(choices=[('draft', '작성중'), ('in_progress', '진행중'), ('completed', '완료'), ('cancelled', '취소'), ('on_hold', '보류'), ('overdue', '지연')], default='draft', max_length=20, verbose_name='상태')),
                ('priority', models.CharField(choices=[('low', '낮음'), ('medium', '보통'), ('high', '높음'), ('urgent', '긴급')], default='medium', max_length=10, verbose_name='우선순위')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='마감일')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='시작일')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_workflows', to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_workflows', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '워크플로우',
                'verbose_name_plural': '워크플로우들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='템플릿명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_default', models.BooleanField(default=False, verbose_name='기본 템플릿')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('steps_config', models.JSONField(default=dict, verbose_name='단계 설정')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '워크플로우 템플릿',
                'verbose_name_plural': '워크플로우 템플릿들',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='단계명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('in_progress', '진행중'), ('completed', '완료'), ('cancelled', '취소'), ('on_hold', '보류')], default='pending', max_length=20, verbose_name='상태')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='마감일')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='시작일')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflow.workflow', verbose_name='워크플로우')),
            ],
            options={
                'verbose_name': '워크플로우 단계',
                'verbose_name_plural': '워크플로우 단계들',
                'ordering': ['workflow', 'order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('document_type', models.CharField(choices=[('resume', '이력서'), ('cover_letter', '자기소개서'), ('reference', '추천서'), ('contract', '계약서'), ('other', '기타')], max_length=20, verbose_name='문서 유형')),
                ('file', models.FileField(upload_to='workflow_documents/', verbose_name='파일')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='업로드자')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='workflow.workflow', verbose_name='워크플로우')),
            ],
            options={
                'verbose_name': '워크플로우 문서',
                'verbose_name_plural': '워크플로우 문서들',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(help_text='자동 생성되는 고유 식별자', max_length=20, unique=True, verbose_name='요청 ID')),
                ('position_title', models.CharField(max_length=100, verbose_name='채용 포지션')),
                ('department', models.CharField(max_length=50, verbose_name='부서')),
                ('employment_type', models.CharField(choices=[('full_time', '정규직'), ('part_time', '비정규직'), ('contract', '계약직'), ('intern', '인턴'), ('temporary', '임시직')], max_length=20, verbose_name='고용 형태')),
                ('salary_min', models.IntegerField(blank=True, help_text='연봉 기준 (만원)', null=True, verbose_name='최소 급여')),
                ('salary_max', models.IntegerField(blank=True, help_text='연봉 기준 (만원)', null=True, verbose_name='최대 급여')),
                ('required_experience', models.TextField(verbose_name='필수 경력 요구사항')),
                ('preferred_qualifications', models.TextField(blank=True, verbose_name='우대사항')),
                ('job_description', models.TextField(verbose_name='업무 내용')),
                ('working_hours', models.CharField(blank=True, max_length=100, verbose_name='근무 시간')),
                ('working_location', models.CharField(blank=True, max_length=200, verbose_name='근무 장소')),
                ('urgency_level', models.CharField(choices=[('high', '높음'), ('medium', '보통'), ('low', '낮음')], default='medium', max_length=10, verbose_name='긴급도')),
                ('status', models.CharField(choices=[('draft', '작성중'), ('submitted', '제출완료'), ('accepted', '접수완료'), ('in_progress', '진행중'), ('completed', '완료'), ('cancelled', '취소'), ('on_hold', '보류')], default='draft', max_length=20, verbose_name='상태')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='제출 시간')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='접수 시간')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requests', to=settings.AUTH_USER_MODEL, verbose_name='요청자')),
            ],
            options={
                'verbose_name': '채용 요청',
                'verbose_name_plural': '채용 요청들',
                'ordering': ['-created_at'],
            },
        ),
    ]
