# Generated by Django 4.2.7 on 2025-07-07 02:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.CharField(choices=[('job_request', '채용 요청'), ('job_posting', '구인 공고'), ('candidate_collection', '지원자 모집'), ('document_screening', '서류 심사'), ('interview_scheduling', '면접 일정 조율'), ('interview', '면접 진행'), ('evaluation', '면접 평가'), ('final_decision', '최종 결정'), ('hiring', '채용 확정')], default='job_request', max_length=30, verbose_name='현재 단계')),
                ('step_completion_rate', models.IntegerField(default=0, help_text='0-100%', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='단계 완료율')),
                ('overall_progress', models.IntegerField(default=0, help_text='0-100%', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='전체 진행률')),
                ('estimated_completion_date', models.DateField(blank=True, null=True, verbose_name='예상 완료일')),
                ('actual_completion_date', models.DateField(blank=True, null=True, verbose_name='실제 완료일')),
                ('target_completion_date', models.DateField(help_text='2주 이내 완료 목표', verbose_name='목표 완료일')),
                ('bottlenecks', models.JSONField(default=list, help_text='진행을 막고 있는 문제점들', verbose_name='병목 지점')),
                ('total_candidates', models.IntegerField(default=0, verbose_name='총 지원자 수')),
                ('screened_candidates', models.IntegerField(default=0, verbose_name='서류 심사 완료 수')),
                ('interviewed_candidates', models.IntegerField(default=0, verbose_name='면접 완료 수')),
                ('hired_candidates', models.IntegerField(default=0, verbose_name='채용 확정 수')),
                ('step_start_times', models.JSONField(default=dict, verbose_name='단계별 시작 시간')),
                ('step_end_times', models.JSONField(default=dict, verbose_name='단계별 완료 시간')),
                ('step_durations', models.JSONField(default=dict, verbose_name='단계별 소요 시간')),
                ('is_on_track', models.BooleanField(default=True, verbose_name='일정 준수 여부')),
                ('is_completed', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('job_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_progress', to='workflow.jobrequest', verbose_name='채용 요청')),
            ],
            options={
                'verbose_name': '워크플로우 진행 상황',
                'verbose_name_plural': '워크플로우 진행 상황들',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_id', models.CharField(help_text='자동 생성되는 고유 식별자', max_length=20, unique=True, verbose_name='공고 ID')),
                ('title', models.CharField(max_length=200, verbose_name='공고 제목')),
                ('summary', models.TextField(verbose_name='공고 요약')),
                ('detailed_description', models.TextField(verbose_name='상세 설명')),
                ('requirements', models.TextField(verbose_name='자격 요건')),
                ('preferred_qualifications', models.TextField(blank=True, verbose_name='우대사항')),
                ('benefits', models.TextField(blank=True, verbose_name='복리후생')),
                ('posting_date', models.DateTimeField(verbose_name='게시일')),
                ('closing_date', models.DateTimeField(verbose_name='마감일')),
                ('application_deadline', models.DateTimeField(verbose_name='지원 마감일')),
                ('status', models.CharField(choices=[('draft', '작성중'), ('published', '게시중'), ('paused', '일시중지'), ('closed', '마감'), ('expired', '만료')], default='draft', max_length=20, verbose_name='공고 상태')),
                ('is_featured', models.BooleanField(default=False, verbose_name='주요 공고')),
                ('view_count', models.IntegerField(default=0, verbose_name='조회수')),
                ('application_count', models.IntegerField(default=0, verbose_name='지원자 수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='게시일')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('job_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_posting', to='workflow.jobrequest', verbose_name='채용 요청')),
            ],
            options={
                'verbose_name': '구인 공고',
                'verbose_name_plural': '구인 공고들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(max_length=20, unique=True, verbose_name='지원 ID')),
                ('cover_letter', models.TextField(verbose_name='자기소개서')),
                ('resume_file', models.FileField(upload_to='applications/resumes/', verbose_name='이력서')),
                ('portfolio_file', models.FileField(blank=True, upload_to='applications/portfolios/', verbose_name='포트폴리오')),
                ('status', models.CharField(choices=[('submitted', '지원완료'), ('under_review', '검토중'), ('shortlisted', '서류합격'), ('rejected', '서류불합격'), ('withdrawn', '지원철회')], default='submitted', max_length=20, verbose_name='지원 상태')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='지원일')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='검토일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='지원자')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='workflow.jobposting', verbose_name='구인 공고')),
            ],
            options={
                'verbose_name': '구인 공고 지원',
                'verbose_name_plural': '구인 공고 지원들',
                'ordering': ['-submitted_at'],
                'unique_together': {('job_posting', 'applicant')},
            },
        ),
    ]
