# Generated by Django 4.2.7 on 2025-07-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_workflowprogress_jobposting_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='job_posting_image',
            field=models.ImageField(blank=True, help_text='채용 공고 스크린샷 또는 관련 이미지', null=True, upload_to='job_postings/', verbose_name='채용 공고 이미지'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='job_posting_platform',
            field=models.CharField(blank=True, help_text='예: 잡코리아, 사람인, 인크루트 등', max_length=50, verbose_name='게시 플랫폼'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='job_posting_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='채용 공고 제목'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='job_posting_url',
            field=models.URLField(blank=True, help_text='실제 채용 공고가 게시된 URL', null=True, verbose_name='채용 공고 링크'),
        ),
    ]
