# Generated by Django 4.2.7 on 2025-07-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_workflowstep_job_posting_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowstep',
            name='job_posting_image',
        ),
        migrations.RemoveField(
            model_name='workflowstep',
            name='job_posting_platform',
        ),
        migrations.RemoveField(
            model_name='workflowstep',
            name='job_posting_title',
        ),
        migrations.RemoveField(
            model_name='workflowstep',
            name='job_posting_url',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='posting_image',
            field=models.ImageField(blank=True, help_text='채용 공고 스크린샷 또는 관련 이미지', null=True, upload_to='job_postings/', verbose_name='채용 공고 이미지'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='posting_platform',
            field=models.CharField(blank=True, help_text='예: 잡코리아, 사람인, 인크루트 등', max_length=50, verbose_name='게시 플랫폼'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='posting_url',
            field=models.URLField(blank=True, help_text='실제 채용 공고가 게시된 URL', null=True, verbose_name='채용 공고 링크'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='expected_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='희망 입사일'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='hospital_address',
            field=models.TextField(default='', verbose_name='병원 주소'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='hospital_branch',
            field=models.CharField(default='', max_length=50, verbose_name='지점명'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='hospital_contact_person',
            field=models.CharField(default='', max_length=50, verbose_name='담당자명'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='hospital_name',
            field=models.CharField(default='', max_length=100, verbose_name='병원명'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='hospital_phone',
            field=models.CharField(default='', max_length=20, verbose_name='병원 연락처'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='recruitment_period',
            field=models.CharField(blank=True, max_length=50, verbose_name='채용 기간'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='special_requirements',
            field=models.TextField(blank=True, verbose_name='특별 요청사항'),
        ),
    ]
