# Generated by Django 4.2.7 on 2025-07-07 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0004_remove_workflowstep_job_posting_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='additional_requests',
            field=models.JSONField(blank=True, default=list, verbose_name='추가 요청사항'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='요청이 잠기면 수정할 수 없습니다', verbose_name='요청 잠금'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='잠금 시간'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_job_requests', to=settings.AUTH_USER_MODEL, verbose_name='잠금 처리자'),
        ),
    ]
