# Generated by Django 4.2.7 on 2025-07-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_jobrequest_additional_requests_jobrequest_is_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('pending', '대기중'), ('in_progress', '진행중'), ('completed', '완료'), ('cancelled', '취소'), ('on_hold', '보류')], max_length=20, null=True, verbose_name='이전 상태'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='status_history',
            field=models.JSONField(default=list, verbose_name='상태 변경 히스토리'),
        ),
    ]
