# Generated by Django 4.2.7 on 2025-07-07 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0006_workflowstep_previous_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='템플릿명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_default', models.BooleanField(default=False, verbose_name='기본 템플릿')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('hospital_name', models.CharField(default='', max_length=100, verbose_name='병원명')),
                ('hospital_branch', models.CharField(default='', max_length=50, verbose_name='지점명')),
                ('hospital_address', models.TextField(default='', verbose_name='병원 주소')),
                ('hospital_phone', models.CharField(default='', max_length=20, verbose_name='병원 연락처')),
                ('hospital_contact_person', models.CharField(default='', max_length=50, verbose_name='담당자명')),
                ('position_title', models.CharField(max_length=100, verbose_name='채용 포지션')),
                ('department', models.CharField(max_length=50, verbose_name='부서')),
                ('employment_type', models.CharField(choices=[('full_time', '정규직'), ('part_time', '비정규직'), ('contract', '계약직'), ('intern', '인턴'), ('temporary', '임시직')], max_length=20, verbose_name='고용 형태')),
                ('salary_min', models.IntegerField(blank=True, help_text='연봉 기준 (만원)', null=True, verbose_name='최소 급여')),
                ('salary_max', models.IntegerField(blank=True, help_text='연봉 기준 (만원)', null=True, verbose_name='최대 급여')),
                ('required_experience', models.TextField(verbose_name='필수 경력 요구사항')),
                ('preferred_qualifications', models.TextField(blank=True, verbose_name='우대사항')),
                ('job_description', models.TextField(verbose_name='업무 내용')),
                ('working_hours', models.CharField(blank=True, max_length=100, verbose_name='근무 시간')),
                ('working_location', models.CharField(blank=True, max_length=200, verbose_name='근무 장소')),
                ('special_requirements', models.TextField(blank=True, verbose_name='특별 요청사항')),
                ('expected_start_date', models.DateField(blank=True, null=True, verbose_name='희망 입사일')),
                ('recruitment_period', models.CharField(blank=True, max_length=50, verbose_name='채용 기간')),
                ('urgency_level', models.CharField(choices=[('high', '높음'), ('medium', '보통'), ('low', '낮음')], default='medium', max_length=10, verbose_name='긴급도')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '채용 요청 템플릿',
                'verbose_name_plural': '채용 요청 템플릿들',
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
