# Generated by Django 4.2.7 on 2025-07-07 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_branch_user_branch'),
        ('workflow', '0007_jobrequesttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequesttemplate',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='지점별 템플릿 관리 (선택사항)', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.branch', verbose_name='소속 지점'),
        ),
    ]
