# Generated by Django 4.2.7 on 2025-07-07 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0008_jobrequesttemplate_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('status_change', '상태 변경'), ('status_revert', '상태 되돌리기'), ('step_complete', '단계 완료'), ('step_revert', '단계 되돌리기'), ('note_add', '메모 추가'), ('note_edit', '메모 수정'), ('assignment_change', '담당자 변경'), ('due_date_change', '마감일 변경'), ('workflow_create', '워크플로우 생성'), ('workflow_edit', '워크플로우 수정'), ('workflow_delete', '워크플로우 삭제'), ('step_create', '단계 생성'), ('step_edit', '단계 수정'), ('step_delete', '단계 삭제')], max_length=20, verbose_name='액션 유형')),
                ('action_description', models.TextField(verbose_name='액션 설명')),
                ('old_value', models.TextField(blank=True, verbose_name='이전 값')),
                ('new_value', models.TextField(blank=True, verbose_name='새 값')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='실행 시간')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('user_agent', models.TextField(blank=True, verbose_name='사용자 에이전트')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='실행자')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='workflow.workflowstep', verbose_name='워크플로우 단계')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='workflow.workflow', verbose_name='워크플로우')),
            ],
            options={
                'verbose_name': '워크플로우 액션 로그',
                'verbose_name_plural': '워크플로우 액션 로그들',
                'ordering': ['-performed_at'],
            },
        ),
    ]
