# Generated by Django 4.2.7 on 2025-07-07 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0009_workflowactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='activity_count',
            field=models.IntegerField(default=0, verbose_name='활동 횟수'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='hospital_review_notes',
            field=models.TextField(blank=True, verbose_name='병원 담당 검토 메모'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='hospital_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='병원 담당 확인 시간'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='is_being_monitored',
            field=models.BooleanField(default=True, verbose_name='모니터링 활성화'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마지막 활동 시간'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='review_notes',
            field=models.TextField(blank=True, verbose_name='채용담당 검토 메모'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='채용담당 확인 시간'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='reviewed_by_headhunting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_job_requests', to=settings.AUTH_USER_MODEL, verbose_name='채용담당 확인자'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='reviewed_by_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_reviewed_job_requests', to=settings.AUTH_USER_MODEL, verbose_name='병원 담당 확인자'),
        ),
    ]
