# Generated by Django 4.2.7 on 2025-07-07 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useractivity_related_object_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='지점명')),
                ('address', models.TextField(verbose_name='지점 주소')),
                ('phone', models.CharField(max_length=20, verbose_name='지점 전화번호')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='지점 이메일')),
                ('manager_name', models.CharField(blank=True, max_length=50, verbose_name='지점장명')),
                ('manager_phone', models.CharField(blank=True, max_length=20, verbose_name='지점장 연락처')),
                ('description', models.TextField(blank=True, verbose_name='지점 설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='accounts.organization', verbose_name='소속 기관')),
            ],
            options={
                'verbose_name': '지점',
                'verbose_name_plural': '지점들',
                'ordering': ['organization', 'name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.branch', verbose_name='소속 지점'),
        ),
    ]
