# Generated by Django 4.2.7 on 2025-07-07 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_branch_user_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='병원명')),
                ('address', models.TextField(verbose_name='병원 주소')),
                ('phone', models.CharField(max_length=20, verbose_name='병원 연락처')),
                ('website', models.URLField(blank=True, null=True, verbose_name='웹사이트')),
                ('description', models.TextField(blank=True, verbose_name='병원 설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', verbose_name='소속 기관')),
            ],
            options={
                'verbose_name': '병원',
                'verbose_name_plural': '병원들',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PositionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='포지션명')),
                ('department', models.CharField(max_length=50, verbose_name='부서')),
                ('employment_type', models.CharField(choices=[('full_time', '정규직'), ('part_time', '비정규직'), ('contract', '계약직'), ('intern', '인턴'), ('temporary', '임시직')], max_length=20, verbose_name='고용 형태')),
                ('salary_min', models.IntegerField(blank=True, null=True, verbose_name='최소 급여 (만원)')),
                ('salary_max', models.IntegerField(blank=True, null=True, verbose_name='최대 급여 (만원)')),
                ('required_experience', models.TextField(verbose_name='필수 경력 요구사항')),
                ('preferred_qualifications', models.TextField(blank=True, verbose_name='우대사항')),
                ('job_description', models.TextField(verbose_name='업무 내용')),
                ('working_hours', models.CharField(blank=True, max_length=100, verbose_name='근무 시간')),
                ('working_location', models.CharField(blank=True, max_length=200, verbose_name='근무 장소')),
                ('special_requirements', models.TextField(blank=True, verbose_name='특별 요청사항')),
                ('recruitment_period', models.CharField(blank=True, max_length=50, verbose_name='채용 기간')),
                ('is_default', models.BooleanField(default=False, verbose_name='기본 템플릿')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '포지션 템플릿',
                'verbose_name_plural': '포지션 템플릿들',
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HospitalBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='지점명')),
                ('address', models.TextField(verbose_name='지점 주소')),
                ('phone', models.CharField(max_length=20, verbose_name='지점 연락처')),
                ('manager_name', models.CharField(max_length=50, verbose_name='담당자명')),
                ('manager_phone', models.CharField(max_length=20, verbose_name='담당자 연락처')),
                ('manager_email', models.EmailField(max_length=254, verbose_name='담당자 이메일')),
                ('business_hours', models.CharField(blank=True, max_length=100, verbose_name='영업시간')),
                ('description', models.TextField(blank=True, verbose_name='지점 설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='accounts.hospital', verbose_name='병원')),
            ],
            options={
                'verbose_name': '병원 지점',
                'verbose_name_plural': '병원 지점들',
                'ordering': ['hospital', 'name'],
                'unique_together': {('hospital', 'name')},
            },
        ),
    ]
