# Generated by Django 4.2.7 on 2025-07-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_hospital_positiontemplate_hospitalbranch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('login', '로그인'), ('logout', '로그아웃'), ('workflow_create', '워크플로우 생성'), ('workflow_update', '워크플로우 수정'), ('workflow_delete', '워크플로우 삭제'), ('step_start', '단계 시작'), ('step_complete', '단계 완료'), ('step_revert', '단계 되돌리기'), ('job_request_create', '채용 요청 생성'), ('job_request_update', '채용 요청 수정'), ('job_request_submit', '채용 요청 제출'), ('job_request_lock', '채용 요청 잠금'), ('job_request_unlock', '채용 요청 잠금 해제'), ('job_request_review', '채용 요청 확인'), ('workflow_create', '워크플로우 생성'), ('additional_request_add', '추가 요청사항 등록'), ('candidate_create', '후보자 생성'), ('candidate_update', '후보자 수정'), ('evaluation_create', '평가 생성'), ('evaluation_update', '평가 수정'), ('report_create', '보고서 생성'), ('report_update', '보고서 수정'), ('document_upload', '문서 업로드'), ('document_delete', '문서 삭제'), ('profile_update', '프로필 수정'), ('password_change', '비밀번호 변경'), ('system_access', '시스템 접근'), ('admin_action', '관리자 작업'), ('other', '기타')], max_length=50, verbose_name='활동 유형'),
        ),
    ]
